# Generated by Django 3.2.8 on 2022-05-30 07:00

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('caption', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(null=True, upload_to='games-titles')),
                ('additionalImage', models.ImageField(blank=True, upload_to='games')),
                ('backgroundImage', models.ImageField(null=True, upload_to='gamesbackground')),
                ('date', models.DateTimeField(auto_now=True)),
                ('slug', models.SlugField(unique=True)),
                ('content', models.TextField(validators=[django.core.validators.MinLengthValidator(10)])),
                ('operating', models.CharField(max_length=100)),
                ('processor', models.CharField(max_length=100)),
                ('memory', models.CharField(max_length=100)),
                ('graphics', models.CharField(max_length=100)),
                ('storage', models.CharField(max_length=100)),
                ('additional', models.CharField(max_length=100)),
                ('downloadlink', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='gameStudio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studioname', models.CharField(max_length=80)),
                ('studioname2', models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=50)),
                ('text', models.CharField(max_length=300)),
                ('like', models.BooleanField()),
                ('dislike', models.BooleanField(default=False)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='gamebit.game')),
            ],
        ),
        migrations.AddField(
            model_name='game',
            name='gameStudio',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='games', to='gamebit.gamestudio'),
        ),
        migrations.AddField(
            model_name='game',
            name='tag',
            field=models.ManyToManyField(to='gamebit.Category'),
        ),
    ]
